In [2]:
import numpy as np

In [6]:
x_ridge = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y_ridge = np.array([5, 20, 14, 32, 22, 38])

In [7]:
print(x_ridge, ' \n',   x.shape)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]  
 (6, 1)


In [8]:
print(y_ridge, '\n', y.shape)

[ 5 20 14 32 22 38] 
 (6,)


In [104]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha = 15.5)
ridge_reg.fit(x_ridge, y_ridge)

Ridge(alpha=15.5)

In [105]:
predicted_ridge = ridge_reg.predict(x_ridge)

In [106]:
predicted_ridge

array([ 8.451855  , 13.80444633, 19.15703767, 24.509629  , 29.86222033,
       35.21481167])

In [107]:
r_sq = ridge_reg.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158204358030752


In [108]:
print('intercept:', ridge_reg.intercept_)
print('slope:', ridge_reg.coef_)

intercept: 5.775559331634092
slope: [0.53525913]


In [109]:
import pandas as pd
pred_vs_actual = pd.DataFrame({'Predicted': np.array(predicted_ridge), 'Actual': y})

In [110]:
pred_vs_actual

Predicted  Actual
0   8.451855       5
1  13.804446      20
2  19.157038      14
3  24.509629      32
4  29.862220      22
5  35.214812      38

In [160]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha = 7)

In [161]:
lasso_reg.fit(x, y)

Lasso(alpha=7)

In [162]:
predicted_lasso = lasso_reg.predict(x)

In [163]:
r_sq = lasso_reg.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7144615384615385


In [164]:
import pandas as pd
pred_vs_actual = pd.DataFrame({'Predicted': np.array(predicted_lasso), 'Actual': y})

In [165]:
pred_vs_actual

Predicted  Actual
0   8.933333       5
1  14.093333      20
2  19.253333      14
3  24.413333      32
4  29.573333      22
5  34.733333      38

In [169]:
from sklearn.linear_model import ElasticNet
regr = ElasticNet(alpha=0.01)
regr.fit(x, y)

ElasticNet(alpha=0.01)

In [170]:
r_sq = regr.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158756120369816


In [172]:
predicted_elasticnet = regr.predict(x)

In [174]:
import pandas as pd
pred_vs_actual = pd.DataFrame({'Predicted': np.array(predicted_elasticnet), 'Actual': y})

In [175]:
pred_vs_actual

Predicted  Actual
0   8.333993       5
1  13.733729      20
2  19.133465      14
3  24.533201      32
4  29.932937      22
5  35.332673      38